info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post: {}
  /api/orders:
    get: 
      consumes:
      - application/json 
      description: get all orders
      parameters:
      - description: 
    post: 
      consumes:
        - application/json
        description: add by json account
        parameters:
        - description: Add account
          in: body
          name: account
          required: true
          schema:
            $ref: '#/definitions/model.AddAccount'
            type: object
        produces:
        - application/json
        responses:
          "200":
            description: OK
            schema:
              $ref: '#/definitions/model.Account'
          "400":
            description: Bad Request
            schema:
              $ref: '#/definitions/httputil.HTTPError'
          "404":
            description: Not Found
            schema:
              $ref: '#/definitions/httputil.HTTPError'
          "500":
            description: Internal Server Error
            schema:
              $ref: '#/definitions/httputil.HTTPError'
        summary: Add a account
        tags:
        - accounts
  /api/orders/{id}:
    get: {}
  /api/orders/{id}:
    put: {}
  /api/orders/{id}:
    delete: {}
swagger: "2.0"
